
services:
  main:
    build: .
    restart: unless-stopped
    environment:
      - DOWNLOAD_LOCATION=/mnt/disks/filestorage/videos
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_HOST=redis_db
      - SERVER_URL=bergheisen.com
      - YTDL_HOST=provider
      - VIDEO_DOWNLOAD_SIZE_LIMIT_MEGABYTES=200
      - RATE_LIMITER_RATE=5000
      - RATE_LIMITER_THRESHOLD=10
    volumes:
      - video-volume:/videos
    networks:
      - application-network

  ytdl_provider:
    build: ytdl_provider/
    restart: unless-stopped
    hostname: provider
    environment:
      - DOWNLOAD_FOLDER=/videos
    volumes:
      - video-volume:/videos
    networks:
      - application-network
  redis_db:
    hostname: redis_db
    image: redis:latest
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data_container:/data
    networks:
      - application-network


networks:
  application-network:

volumes:
  video-volume:
  redis_data_container:
